### ISSUE TITLE
Problem with shift-select *when it is the first operation on the sheet*

### ISSUE THREAD

**Issue by KirklandBordeaux** [ragardner/tksheet#106]
ragardner:

I encountered what I think is a bug. When shift-select is the **first** operation on a sheet, it raises an error. If anything else happens first, like selecting a cell, shift-select works fine. Here is a sample code that demonstrates the error (based on a slimmed-down version of one of your sample files):
```
from tksheet import Sheet
import tkinter as tk

class demo(tk.Tk):
    def __init__(self):
        tk.Tk.__init__(self)
        self.grid_columnconfigure(0, weight = 1)
        self.grid_rowconfigure(0, weight = 1)
        self.frame = tk.Frame(self)
        self.frame.grid_columnconfigure(0, weight = 1)
        self.frame.grid_rowconfigure(0, weight = 1)
        self.sheet = Sheet(self.frame,
                           page_up_down_select_row = True,
                           column_width = 120,
                           startup_select = (0,1,"rows"),
                           data = [[f"Row {r}, Column {c}\nnewline1\nnewline2" for c in range(50)] for r in range(500)], #to set sheet data at startup
                           height = 500, #height and width arguments are optional
                           width = 1200 #For full startup arguments see DOCUMENTATION.md
                           )
 
        self.sheet.enable_bindings(("single_select", #"single_select" or "toggle_select"
                                         "drag_select",   #enables shift click selection as well
                                         "column_drag_and_drop",
                                         "row_drag_and_drop",
                                         "column_select",
                                         "row_select",
                                         "column_width_resize",
                                         "double_click_column_resize",
                                          "arrowkeys",
                                         "row_height_resize",
                                         "double_click_row_resize",
                                         "right_click_popup_menu",
                                         "rc_select",
                                         "rc_insert_column",
                                         "rc_delete_column",
                                         "rc_insert_row",
                                         "rc_delete_row",
                                         "hide_columns",
                                         "copy",
                                         "cut",
                                         "paste",
                                         "delete",
                                         "undo",
                                         "edit_cell"))

        self.frame.grid(row = 0, column = 0, sticky = "nswe")
        self.sheet.grid(row = 0, column = 0, sticky = "nswe")
        
        self.sheet.extra_bindings([("shift_cell_select", self.shift_select_cells)])

    def shift_select_cells(self, response):
        print (response)

app = demo()
app.mainloop()
```

Here is the error message that is raised:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ExpManDevEnv/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/opt/anaconda3/envs/ExpManDevEnv/lib/python3.9/site-packages/tksheet/_tksheet_main_table.py", line 2331, in shift_b1_press
    self.shift_selection_binding_func(SelectionBoxEvent("shift_select_cells", tuple(int(e) for e in self.gettags(self.find_withtag("CellSelectFill"))[1].split("_") if e)))
IndexError: tuple index out of range
```

Thanks,

KB

**Comment by ragardner** [comment]
Thanks very much for the report, it should be fixed in `5.3.0`
