### ISSUE TITLE
Sheet.font() method issue

### ISSUE THREAD

**Issue by silantyev** [ragardner/tksheet#34]
`self.sheet.font(('Calibri', 9, 'normal'))`
raises an error.
Traceback:
Traceback (most recent call last):

  File "<ipython-input-5-6dd9384721c8>", line 1, in <module>
    runfile('C:/Users/admin/DS/Rugby/API/RLstat.pyw', wdir='C:/Users/admin/DS/Rugby/API')

  File "C:\Users\admin\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\admin\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/admin/DS/Rugby/API/RLstat.pyw", line 794, in <module>
    window = MainWindow(application)

  File "C:/Users/admin/DS/Rugby/API/RLstat.pyw", line 275, in __init__
    self.teams_stats_sheet.font(('Calibri', 9, 'normal'))

  File "C:\Users\admin\Anaconda3\lib\site-packages\tksheet\_tksheet.py", line 1357, in font
    self.MT.font(newfont)

  File "C:\Users\admin\Anaconda3\lib\site-packages\tksheet\_tksheet_main_table.py", line 2279, in font
    raise ValueError("Parameter must be three-tuple")

ValueError: Parameter must be three-tuple

Cause:
In `MainTable.font()` method there is a condition `if len(newfont) > 2:`, so that expected length of the newfont (3) raises an error.

Solution:
Change `if len(newfont) > 2:` by `if len(newfont) != 3:`

I also would like to propose to change:
```
if (
                not isinstance(newfont, tuple) or
                not isinstance(newfont[0], str) or
                not isinstance(newfont[1], int)
                ):
```
by
```
if (
                not isinstance(newfont, tuple) or
                len(newfont) < 2 or
                not isinstance(newfont[0], str) or
                not isinstance(newfont[1], int)
                ):
```

**Comment by ragardner** [comment]
@silantyev Sorry about the bug and thanks for the suggestions, it should be fixed in `4.9.7` but let me know if you encounter any more issues
