### ISSUE TITLE
An error occurred when adding a new column to a table if it initially contains a data column

### ISSUE THREAD

**Issue by bnxvs** [ragardner/tksheet#59]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1884, in __call__
    return self.func(*args)
  File "/Users/bnx/PycharmProjects/tkinter_study/main_new.py", line 93, in add_col_table
    table_input.insert_column()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tksheet/_tksheet.py", line 1870, in insert_column
    self.MT.cell_options = {(rn, cn if cn < idx else cn + 1): t2 for (rn, cn), t2 in self.MT.cell_options.items()}
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tksheet/_tksheet.py", line 1870, in <dictcomp>
    self.MT.cell_options = {(rn, cn if cn < idx else cn + 1): t2 for (rn, cn), t2 in self.MT.cell_options.items()}
TypeError: '<' not supported between instances of 'int' and 'str'

![Снимок экрана 2021-02-15 в 18 27 41](https://user-images.githubusercontent.com/49068521/107947019-026a7c80-6fbc-11eb-9973-4cbcb851cb7c.png)

If I delete an existing column, the creation of new ones does not cause such an error.

**Comment by ragardner** [comment]
Sorry about the bug

It should hopefully be fixed in version `5.0.0`

**Comment by bnxvs** [comment]
Thanks a lot!
